### ISSUE TITLE
Notations are not shown for ancestor/narrower concepts

### ISSUE THREAD

**Issue by stefandesu** [gbv/jskos-proxy#10]
Notations should be shown in front of concept labels as usual (i.e. as defined in `DISPLAY.hideNotation` for the concept scheme).

<img width="691" alt="Screen Shot 2023-05-08 at 10 31 53" src="https://user-images.githubusercontent.com/3275148/236776021-6ad25105-5ac8-4c3b-908c-3586c29b9bc9.png">

**Comment by nichtich** [comment]
narrower/broader concepts don't include notations by default when returned via DANTE API (see <http://api.dante.gbv.de/data/data?uri=http%3A%2F%2Furi.gbv.de%2Fterminology%2Fbk%2F05.00&properties=*>). Missing information should be loaded using cocoda-sdk as done in Cocoda.
