### ISSUE TITLE
External uri's not working for single records

### ISSUE THREAD

**Issue by StiftungAusNachlass** [gbv/jskos-proxy#24]
If the URI is an external URI, then the application does not resolve it.

Example: https://uri.gbv.de/terminology/?uri=https://obersuperdatensatz23.gbv.de

That is: https://api.dante.gbv.de/data?uri=https%3A%2F%2Fobersuperdatensatz23.gbv.de&properties=*&cache=0

**Comment by nichtich** [comment]
This is a nasty edge case. It's not because the URI is external but because <https://obersuperdatensatz23.gbv.de> is normalized to URL <https://obersuperdatensatz23.gbv.de/> by [Node URL](https://nodejs.org/api/url.html#class-url).

**Comment by StiftungAusNachlass** [comment]
Waah, sounds ugly. But https://obersuperdatensatz23.gbv.de is a valid URI.
The URL parameter is usually encoded. Above is only in standard form.
Why is Node normalizing an encoded url here? It should actually go into the parameter without any manipulation.

Ok - does not matter. There will never be a URI ending with just the tld. I changed to https://uri.gbv.de/terminology/?uri=https://obersuperdatensatz23.gbv.de/123 and that works..
