### ISSUE TITLE
Configure Favicon

### ISSUE THREAD

**Issue by nichtich** [gbv/jskos-proxy#32]
At https://uri.gbv.de/terminology/sondengaenger_fundart/ the Vite Favicon is shown instead.

**Comment by nichtich** [comment]
Yes, it should come from the config directory, e.g. https://github.com/gbv/jskos-proxy/tree/main/config/uri.gbv.de/

**Comment by stefandesu** [comment]
A favicon can now be configured by providing a `favicon.ico` inside the config directory. GBV favicon is still used as fallback/default.
