### ISSUE TITLE
subset behavior

### ISSUE THREAD

**Issue by StiftungAusNachlass** [gbv/jskos-proxy#33]
The subsets do not work as users expect.
Example: https://uri.gbv.de/terminology/subset_nld_nfis_events/
This is a subset from https://uri.gbv.de/terminology/object_related_event/
Every time you click on the left on a data record in the subset, you leave the subset and end up in the other vocabulary. This behavior was apparently different before and therefore better.

**Comment by stefandesu** [comment]
Should be fixed in Dev: https://coli-conc.gbv.de/terminology/subset_nld_nfis_events/

Will create a release later today.
