### ISSUE TITLE
Show distributions to download vocabularies

### ISSUE THREAD

**Issue by nichtich** [gbv/jskos-proxy#35]
A common request is where to download a vocabulary. This information is included in field `distribution` for some vocabularies for instance http://uri.gbv.de/terminology/bk/ so it should also be shown.

**Comment by stefandesu** [comment]
How should the distributions be displayed? For BK, there are eight different items in the `distributions` fields: http://localhost:3555/terminology/bk/?format=jskos They are not really labeled well and sometimes differ only by the download URL. Any ideas?

**Comment by nichtich** [comment]
Items could be shown like this:

- [2024-03-02](https://api.dante.gbv.de/export/download/bk/default/) ([JSKOS](http://format.gbv.de/jskos), 7 MB) Full export of all available formats with all properties

if `created` is missing use fallback label "download". The format names should be hardcoded. Full list is available via

    curl -s https://format.gbv.de/formats.ndjson | jq -c '{key:("http://format.gbv.de/"+.id),value:.title}' | jq -Ss 'from_entries'

but DANTE only supports a hand full of these formats.

**Comment by stefandesu** [comment]
Can you check https://coli-conc.gbv.de/terminology/ for the current implementation @nichtich?

**Comment by nichtich** [comment]
Works as expected. Only the label "Distributionen"/"Distributions" should be changed to "Download".
