### ISSUE TITLE
Display geographic information

### ISSUE THREAD

**Issue by nichtich** [gbv/jskos-proxy#38]
Requires good examples.

**Comment by stefandesu** [comment]
There should already be a working (simple) map view when a single coordinate is given via `concept.location.coordinates`, but as mentioned, we need some examples.

**Comment by nichtich** [comment]
Example https://uri.gbv.de/terminology/test/21994501-b31d-4bef-bdad-da11cce4c7e8

jskos-proxy needs to explicitly ask dante API for `location` property:

https://api.dante.gbv.de/data?uri=https://uri.gbv.de/terminology/test/21994501-b31d-4bef-bdad-da11cce4c7e8&properties=location

**Comment by stefandesu** [comment]
Now implemented in Dev. Two issues:

- If only a point is given, the zoom level is extremely small, see for example: https://coli-conc.gbv.de/terminology/ikmk_ort/?uri=https%3A%2F%2Fikmk.smb.museum%2Fndp%2Fort%2F104 However, how can we determine an appropriate zoom level?
- For the given example, the field `location` is, for some reason, not loaded: https://coli-conc.gbv.de/terminology/test/21994501-b31d-4bef-bdad-da11cce4c7e8 This should be a DANTE issue: https://api.dante.gbv.de/voc/top?properties=+location&uri=http:%2F%2Furi.gbv.de%2Fterminology%2Ftest%2F

**Comment by StiftungAusNachlass** [comment]
The field location is not loaded in the example, because the example is from testpool and there is a special situation with different masks. This behaviour is different in "real" / "prod" - Pools. 
Use for example: https://api.dante.gbv.de/voc/top?uri=http:%2F%2Furi.gbv.de%2Fterminology%2Fprizepapers_place%2F&cache=false&properties=+location&limit=50

**Comment by StiftungAusNachlass** [comment]
Zoom: in our plugins we use zoom level 15 for points. For polygons so far into the bounds that there is still a bit of edge everywhere..

**Comment by stefandesu** [comment]
I've set the default zoom level to 15 for Points. For many examples, it still seems way too far zoomed in though.

Other than that, all GeoJSON data supported by [Leaflet](https://leafletjs.com/) should work now. Other than the example from the test pool that does not load the `location` field, do we have examples for other location types than `Point`?

Also, can we expect there to be always one element in `location`, and if not, can you provide examples when there are multiples? Currently, it should show multiple maps, but it would be better to show all data in one map.

**Comment by StiftungAusNachlass** [comment]
Here a polygon-example: https://api.dante.gbv.de/data?uri=https://uri.gbv.de/terminology/prizepapers_place/ebf8ca1f-2218-4cf4-9d8c-ec545dd1b450&properties=+location
LineString is also allowed in DANTE, but used very rarely. multiple geoJSONs are also possible, but probably not used anywhere.

**Comment by StiftungAusNachlass** [comment]
No information comes from DANTE as to what type of place it is. Theoretically we have fields “geonames-Type” and “gnd-place-type”, but nobody uses them. I think the only option would be to use a geocoding service. Reverse. 

You could try: https://nominatim.openstreetmap.org/ui/reverse.html?lat=42.33665&lon=13.49121&zoom=18

**Comment by stefandesu** [comment]
Even then it would be basically impossible to say whether a certain coordinate is meant to show the whole city or just one specific building in the center of the city. I guess I'll leave it at that for now.
