### ISSUE TITLE
Edge cases where showing geographic information does not work

### ISSUE THREAD

**Issue by stefandesu** [gbv/jskos-proxy#44]
Found this edge case where MapView doesn't show the location: https://uri.gbv.de/terminology/areal_unit_bremen/7ec16302-1c85-48e4-9d1b-6f47ef1322ad

Not sure if this is an issue with the GeoJSON or with my implementation.

#38

**Comment by stefandesu** [comment]
The location data coming from the API has type "Polygon", but is structured like "MultiPolygon". Manually overriding the type to "MultiPolygon" causes it to work correctly. @StiftungAusNachlass Can you check this and possibly correct the data?

**Comment by StiftungAusNachlass** [comment]
I fixed that in API. https://uri.gbv.de/terminology/areal_unit_bremen/7ec16302-1c85-48e4-9d1b-6f47ef1322ad is served as MultiPolygon now and is shown correctly.

**Comment by stefandesu** [comment]
@StiftungAusNachlass I have found examples where the opposite is now the case, i.e. data is structured like "Polygon", but has type "MultiPolygon".

Some examples:
- http://uri.gbv.de/terminology/areal_unit_niedersachsen/d765e444-03dd-46e4-96cd-82fb4665ae8d ([API](https://api.dante.gbv.de/data?uri=http://uri.gbv.de/terminology/areal_unit_niedersachsen/d765e444-03dd-46e4-96cd-82fb4665ae8d&properties=location))
- http://uri.gbv.de/terminology/areal_unit_niedersachsen/0365acdf-2348-4801-87eb-80470cc9cb4f  ([API](https://api.dante.gbv.de/data?uri=http://uri.gbv.de/terminology/areal_unit_niedersachsen/0365acdf-2348-4801-87eb-80470cc9cb4f&properties=location))
- http://uri.gbv.de/terminology/areal_unit_niedersachsen/7f92fa45-f668-437a-8275-4eebb4899c94 ([API](https://api.dante.gbv.de/data?uri=http://uri.gbv.de/terminology/areal_unit_niedersachsen/7f92fa45-f668-437a-8275-4eebb4899c94&properties=location))

Do you think it's possible to fix all these issues in the API, or should I also include some code tries to detect and fix the Polygon/MultiPolygon issue if it occurs?

**Comment by nichtich** [comment]
We also stumbled upon locations with multiple parts, these are encoded as arrays by DANTE API but will be changed to use valid GeoJSON with type `GeometryCollection`.

**Comment by stefandesu** [comment]
I think for jskos-proxy in particular, this shouldn't make a difference. Multiple entries in the `location` property should still all be shown. (I guess it would be good if everything conforms to the JSKOS spec though, which means `location` should be a single GeoJSON object instead of an array. Right now, both variants should work in jskos-proxy.)

The issue with Polygon vs MultiPolygon [above](https://github.com/gbv/jskos-proxy/issues/44#issuecomment-2333576218) still exists.

**Comment by StiftungAusNachlass** [comment]
Ok. I changed the following things:

- according to the spec jskos.location is now always an object. Before it was an array. That's why it no longer works on uri.gbv.de/terminology . A fix there is needed.
- if multiple geojson's are added in DANTE, jskos.location is an geometrycollection-object, as in example above

The examples from [above](https://github.com/gbv/jskos-proxy/issues/44#issuecomment-2333576218) look to me like corrupt data in DANTE. These are not multipolygons, but probably GeometryCollections. So probably a data error during an import. I am auto-fixing some possibly errors now.

**Comment by stefandesu** [comment]
Fixes are released and everything seems to be working as expected now. 🥳
