### ISSUE TITLE
Call via URI

### ISSUE THREAD

**Issue by StiftungAusNachlass** [gbv/jskos-proxy#48]
Hallo,

bisher ist es nicht möglich einen Datensatz nur per URI aufzurufen.

Also z.B. https://uri.gbv.de/terminology/?uri=http://uri.gbv.de/terminology/prizepapers_place/bf729bd7-771c-4e4c-a45c-2b5ff5028891

Auch nicht in encodierter Form: https://uri.gbv.de/terminology/?uri=https%3A%2F%2Fofficialuri.com%2F1234

Es funktioniert bisher nur mit vorangestelltem Vokabular. Z.B. https://uri.gbv.de/terminology/http%3A%2F%2Fid.loc.gov%2Fvocabulary%2Fiso639-1/?uri=http%3A%2F%2Fid.loc.gov%2Fvocabulary%2Fiso639-1%2Fbm
oder 
https://uri.gbv.de/terminology/prizepapers_place/?uri=http://uri.gbv.de/terminology/prizepapers_place/bf729bd7-771c-4e4c-a45c-2b5ff5028891

Das muss aber auch ohne gehen, weil wir das Vokabularkürzel nicht unbedingt ableiten können und außerdem ging das früher auch :-) 

Danke und viele Grüße!

**Comment by stefandesu** [comment]
Ich schau's mir nächste Woche an, das sollte einfach umsetzbar sein!

**Comment by nichtich** [comment]
Spricht etwas dagegen, das gleich mit Suche zu integrieren? Wenn nach einer URL gesucht wird, sollte bei bekannter URI diese gefunden werden.

**Comment by stefandesu** [comment]
> Spricht etwas dagegen, das gleich mit Suche zu integrieren? Wenn nach einer URL gesucht wird, sollte bei bekannter URI diese gefunden werden.

Das sollte schon funktionieren, nur sind Vokabularsuche und Konzeptsuche weiterhin separat.

**Comment by stefandesu** [comment]
Eine Frage, eine Bitte:

Frage: Wenn eine URI gegeben ist, aber kein Datensatz dazu gefunden wurde, wie soll das vermittelt werden? Ich hab erstmal nur einen Fehler auf der Konsole ausgegeben, aber eine Meldung im Interface wäre ja schon sinnvoll.

Bitte an @StiftungAusNachlass: Die Erkennung, ob eine URI zu einem bestimmten Vokabular passt, funktioniert nur, wenn das Vokabular entweder einen `namespace` oder eine `uriPattern` hat. Das scheint bei DANTE-Vokabularen noch nicht gegeben zu sein (zumindest nicht über die DANTE-API). Könntest du das hinzufügen? Bei den Vokabularen, die URIs aus dem http://uri.gbv.de/terminology/ namespace nutzen, wäre es ja einfach namespace = URI. (Das könnte ich sonst hier auch hardcoden, aber es fühlt sich besser an, wenn die API das direkt richtig mitliefert.)

**Comment by StiftungAusNachlass** [comment]
> Frage: Wenn eine URI gegeben ist, aber kein Datensatz dazu gefunden wurde, wie soll das vermittelt werden? Ich hab erstmal nur einen Fehler auf der Konsole ausgegeben, aber eine Meldung im Interface wäre ja schon sinnvoll.

Ich würde sagen, dass im Frontend eine Meldung "Diese Anfrage führt leider in die Leere" oder dergleichen dargestellt werden sollte.

> Bitte an @StiftungAusNachlass: Die Erkennung, ob eine URI zu einem bestimmten Vokabular passt, funktioniert nur, wenn das Vokabular entweder einen `namespace` oder eine `uriPattern` hat. Das scheint bei DANTE-Vokabularen noch nicht gegeben zu sein (zumindest nicht über die DANTE-API). Könntest du das hinzufügen? Bei den Vokabularen, die URIs aus dem http://uri.gbv.de/terminology/ namespace nutzen, wäre es ja einfach namespace = URI. (Das könnte ich sonst hier auch hardcoden, aber es fühlt sich besser an, wenn die API das direkt richtig mitliefert.)

Die Vokabulare haben jetzt alle den passenden namespace.

**Comment by stefandesu** [comment]
> Die Vokabulare haben jetzt alle den passenden namespace. Das ist fast immer uri.gbv.de/terminology/vocname/. Außer in den Fällen, in denen explizit ein anderer namespace angegeben ist.

Super, vielen Dank!

Es sollte jetzt funktionieren, aber schließe ich das Issue, jedoch kämpfe ich noch mit zwei kleinen Bugs, die nicht direkt mit diesem Issue zusammenhängen, aber sich dadurch zeigen.

**Comment by stefandesu** [comment]
Ich bräuchte ein konkretes Beispiel. Wenn es nicht funktioniert, ist es entweder ein Bug (dann fixe ich ihn), oder (aus meiner Sicht wahrscheinlicher) fehlt das `namespace` Feld in den Daten des Vokabulars. ;)

**Comment by StiftungAusNachlass** [comment]
https://uri.gbv.de/terminology/?uri=https://officialuri.com/1234_basic

**Comment by stefandesu** [comment]
http://uri.gbv.de/terminology/cron_schedule_expression/ hat den Namespace `http://uri.gbv.de/terminology/cron_schedule_expression/`, aber die URI https://officialuri.com/1234_basic ist trotzdem dem Vokabular untergeordnet? Das scheint mir ein sehr spezieller Fall zu sein.

Was ich machen könnte ist, dass nur in dem Fall, dass zu einer URI kein Vokabular mit passendem Namespace gefunden wurde, eine Anfrage an https://api.dante.gbv.de/data gemacht wird, um zu bestimmen, zu welchem Vokabular es gehört. Das wäre vielleicht auch gut als Backup für die Fälle, wo `namespace` einfach fehlt oder falsch ist.

**Comment by StiftungAusNachlass** [comment]
Hm.... Ja, vielleicht ein spezieller Fall.. Wird aber immer wieder vorkommen, ohne dass wir das mitbekommen. Oder auch, dass Kunden andere URIs verwenden, obwohl ein anderer Namespace verwendet wird.. 

Wäre also klasse, wenn im Fall der Fälle sicherheitshalber noch einmal api.dante.gbv.de/data?uri=xyz geprüft werden würde..

**Comment by stefandesu** [comment]
Done! 👍
