### ISSUE TITLE
Include broader and narrower property in concept download

### ISSUE THREAD

**Issue by nichtich** [gbv/jskos-proxy#50]
Concept download, e.g. http://uri.gbv.de/terminology/kenom_material/6ac5ef46-0eff-4a57-99c3-daadb26ca5bf?format=json for http://uri.gbv.de/terminology/kenom_material/6ac5ef46-0eff-4a57-99c3-daadb26ca5bf does not contain broader (it's `[null]`). The `broader` and `narrower` fields should better be included because the concept download is the only API, there is in endpoint to query narrower or broader concepts individually.

**Comment by stefandesu** [comment]
I added `ancestors` as well. Will be in the next release.
